@startuml
class AutomaticClutch {
    + <<static>> allowedCarryingCapacity : double[]
    + <<static>> allowedUsefulVolume : double[]
    + <<static>> allowedCapacity : double[]
}
Truck <|-- AutomaticClutch
@enduml
