@startuml
class Container {
    + <<static>> allowedCarryingCapacity : double[]
    + <<static>> allowedUsefulVolume : double[]
    + <<static>> allowedCapacity : double[]
}
Truck <|-- Container
@enduml
