@startuml
enum CargoType {
    RequiresRefrigerator,
    DoesNotNeedRefrigerator
}
class CargoTypeConverter {
    + <<static>> dictionary : new() { ... }
}
CargoTypeConverter::dictionary --> CargoType
@enduml
