@startuml
enum TruckType {
    Refrigerated,
    Container,
    AutoClutch,
    Tent
}
class TruckTypeConverter {
    + <<static>> dictionary : new() { ... }
}
TruckTypeConverter::dictionary --> TruckType
@enduml
